version: "3"

services:
  composer:
    image: symfony-4-sonata_web
    cap_drop: [all]
    working_dir: /var/www/html
    entrypoint: composer
    volumes:
      - ./symfony:/var/www/html:cached
  phpunit:
    image: symfony-4-sonata_web
    cap_drop: [all]
    working_dir: /var/www/html
    entrypoint: ./bin/phpunit
    volumes:
      - ./symfony:/var/www/html:cached
