version: "3"

volumes:
  symfony_db:

networks:
  symfony:

services:
  web:
    build:
      context: .
      dockerfile: docker/apache/Dockerfile
    cap_drop: [all]
    cap_add: [chown, setgid, setuid, dac_override, net_bind_service]
    ports:
      - 8001:80
    volumes:
      - ./symfony:/var/www/html:cached
    networks:
      - symfony
  db:
    image: mysql:5.7
    cap_drop: [all]
    cap_add: [chown, setgid, setuid, dac_override]
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3311:3306
    volumes:
      - symfony_db:/var/lib/mysql:cached
    networks:
      - symfony
